### PR TITLE
Fix#10 laozey

### PR DESCRIPTION
**Pull request by Laozey**
Format document
update filenameOf using strrchr in the function
#10

### CODE REVIEW

**Comment by fiplox** [comment]
literally copy of #19 with your own formatting. It is not acceptable to change formatting.

**Comment by darnuria** [comment]
@fiplox Not a reason to be harsh. ;)

@Laozey hey thanks to contribute! As @fiplox said, it's not possible to change the whole formatting of the document. In C there is no "standard" way of formatting files it's like every people like and it's common practice to strive to follow that "convention".

Example: @fiplox wrote `char *p` but in this lib we wrote `char * p` I asked him to change his code to follow established convention.

In rust we have `rustfmt` who do the job for us. But here it's better to avoid doing full-reformatting of the whole file.

About duplicating please manifest yourself in Issues before codding, in the issue discussion we can try to assign issue to peoples and keep track of who want to work on what and avoid "winner takes all" situation where tree students commits altogether on the same issue. xD

**Comment by darnuria** [comment]
@noalien think you can close this one it's mostly a duplicate of @fiplox own PR. @Laozey are you ok? If you want you can review/test the PR of @fiplox to help! :)

**Comment by Laozey** [comment]
@darnuria Yes sure !

**Comment by noalien** [comment]
OK, closed because it's mostly a duplicate of @fiplox own PR.

**Pull request closed without merging**
